[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow_ancho = "C4Nz5x37jYuAvdvoJLKbxLkPmNdz5QiyWbxvsAq4c5s9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/professorcodegeek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 100000